/**
 * stm32f4xx.h — Bridge: old SPL projects include this; redirect to new CMSIS.
 * Generated by build setup script.
 */
#ifndef __STM32F4xx_H
#define __STM32F4xx_H

/* Force new CMSIS device selection if not already set */
#if !defined(STM32F407xx) && !defined(STM32F405xx) && !defined(STM32F429xx)
  #define STM32F407xx
#endif

#include "stm32f407xx.h"          /* full register map (new CMSIS) */
#include <stdint.h>

/* SPL compatibility: __IO is defined in core_cm4.h -> cmsis_gcc.h */
#ifndef __IO
  #define __IO  volatile
#endif
#ifndef __I
  #define __I   volatile const
#endif
#ifndef __O
  #define __O   volatile
#endif

/* ── SPL legacy types (defined in old stm32f4xx.h, not in new CMSIS) ─────── */
typedef enum {RESET = 0, SET = !RESET} FlagStatus, ITStatus;
typedef enum {DISABLE = 0, ENABLE = !DISABLE} FunctionalState;
#define IS_FUNCTIONAL_STATE(STATE) (((STATE) == DISABLE) || ((STATE) == ENABLE))
typedef enum {ERROR = 0, SUCCESS = !ERROR} ErrorStatus;

/* ── IRQ numbers (Cortex-M4 system + STM32F407) ────────────────────────────
   Pulled from stm32f407xx.h IRQn_Type — already included above.            */

/* ── GPIO BSRR compatibility (new CMSIS has single BSRR, old SPL uses BSRRL/BSRRH) */
/* New CMSIS stm32f407xx.h has a single 32-bit BSRR field.
   Old SPL splits it into BSRRL (low 16-bit, SET) and BSRRH (high 16-bit, RESET).
   Fix: GPIOx->BSRRH must be a 16-bit write at offset +2 from BSRR. */
/* We override GPIO_ResetBits in the SPL source instead of aliasing here,
   because a simple #define can't fix the offset/width mismatch. */
#define BSRRL   BSRR

/* ── Clock macros (old SPL expects these, new CMSIS doesn't provide) ───── */
#ifndef HSE_VALUE
  #define HSE_VALUE  ((uint32_t)25000000)   /* 25 MHz external crystal */
#endif
#ifndef HSI_VALUE
  #define HSI_VALUE  ((uint32_t)16000000)   /* 16 MHz internal RC */
#endif
#ifndef HSE_STARTUP_TIMEOUT
  #define HSE_STARTUP_TIMEOUT  ((uint16_t)0x0500)
#endif

/* Legacy SPL macro: USE_STDPERIPH_DRIVER selects stm32f4xx_conf.h */
#ifdef USE_STDPERIPH_DRIVER
  #include "stm32f4xx_conf.h"
#endif

#endif /* __STM32F4xx_H */
