/**
 * stm32f4xx.h — Bridge: old SPL projects include this; redirect to new CMSIS.
 * Generated by build setup script.
 */
#ifndef __STM32F4xx_H
#define __STM32F4xx_H

/* Force new CMSIS device selection if not already set */
#if !defined(STM32F407xx) && !defined(STM32F405xx) && !defined(STM32F429xx)
  #define STM32F407xx
#endif

#include "stm32f407xx.h"          /* full register map (new CMSIS) */
#include <stdint.h>

/* SPL compatibility: __IO is defined in core_cm4.h -> cmsis_gcc.h */
#ifndef __IO
  #define __IO  volatile
#endif
#ifndef __I
  #define __I   volatile const
#endif
#ifndef __O
  #define __O   volatile
#endif

/* Legacy SPL macro: USE_STDPERIPH_DRIVER selects stm32f4xx_conf.h */
#ifdef USE_STDPERIPH_DRIVER
  #include "stm32f4xx_conf.h"
#endif

#endif /* __STM32F4xx_H */
